"""Data collection package for CartolaAI."""

from .api import CartolaAPI, CbfAPI, GatoMestreAPI
from .config import (
    BASE_URL,
    BUDGET,
    CAPTAIN_BONUS,
    CBF_API,
    CURRENT_SEASON,
    DATA_DIR,
    DEFAULT_LIGAS,
    FORMATION,
    GATOMESTRE_BASE,
    POSICAO_NOME,
    PROJECT_ROOT,
    SCOUT_POINTS,
    STATUS,
)
from .current import (
    CurrentSeasonCollectionResult,
    collect_latest_api_data,
    get_cartola_users_mean,
    get_current_market,
    get_current_round,
    get_league_brackets,
    get_odds,
    get_round_players_data_from_cartola,
    missing_rounds,
    preparar_partidas,
)
from .datasets import read_datasets
from .file_manager import (
    CartolaUsersMeanDataset,
    CurrentMarketDataset,
    DatasetFile,
    FileManager,
    LeagueBracketsDataset,
    MatchesDataset,
    OddsDataset,
    PlayersDataset,
)
from .transforms import deduplicate_by_key, safe_filename

__all__ = [
    "BASE_URL",
    "BUDGET",
    "CAPTAIN_BONUS",
    "CBF_API",
    "CURRENT_SEASON",
    "DATA_DIR",
    "DEFAULT_LIGAS",
    "FORMATION",
    "GATOMESTRE_BASE",
    "POSICAO_NOME",
    "PROJECT_ROOT",
    "SCOUT_POINTS",
    "STATUS",
    "CartolaAPI",
    "CartolaUsersMeanDataset",
    "CbfAPI",
    "CurrentMarketDataset",
    "DatasetFile",
    "GatoMestreAPI",
    "FileManager",
    "LeagueBracketsDataset",
    "MatchesDataset",
    "OddsDataset",
    "PlayersDataset",
    "CurrentSeasonCollectionResult",
    "collect_latest_api_data",
    "deduplicate_by_key",
    "get_cartola_users_mean",
    "get_current_market",
    "get_current_round",
    "get_league_brackets",
    "get_odds",
    "get_round_players_data_from_cartola",
    "missing_rounds",
    "preparar_partidas",
    "read_datasets",
    "safe_filename",
]
